name: flutter_enhanced_dialog
description: "A highly customizable and animated dialog solution for Flutter applications."
version: 1.0.0
repository: https://github.com/Mahmoud-Saeed-Mahmoud/flutter_enhanced_dialog
issue_tracker: https://github.com/Mahmoud-Saeed-Mahmoud/flutter_enhanced_dialog/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
